---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bozo
spec:
  minReadySeconds: 5
  replicas: 4
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-a000004
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
